using MediatR;
using SME.SR.Infra;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace SME.SR.Application
{
    public class RelatorioAcompanhamentoFrequenciaUseCase : IRelatorioAcompanhamentoFrequenciaUseCase
    {
        public readonly IMediator mediator;
        public RelatorioAcompanhamentoFrequenciaUseCase(IMediator mediator)
        {
            this.mediator = mediator ?? throw new ArgumentNullException(nameof(mediator));
        }
        public async Task Executar(FiltroRelatorioDto request)
        {
            request.RotaErro = RotasRabbitSGP.RotaRelatoriosComErroAcompanhamentoFrequencia;

            // var filtroRelatorio = request.ObterObjetoFiltro<FiltroAcompanhamentoFrequenciaJustificativaDto>();
            
            // var retornoRelatorio = await mediator.Send(new ObterDadosRelatorioAcompanhamentoFrequenciaCommand(filtroRelatorio));

            // await mediator.Send(new GerarRelatorioAcompanhamentoFrequenciaCommand(retornoRelatorio, request.CodigoCorrelacao));

            var relatorios = new List<RelatorioPlanoAeeDto>();

            relatorios.Add(new RelatorioPlanoAeeDto()
            {
                Cabecalho = new CabecalhoPlanoAeeDto()
                {
                    AlunoCodigo = "7583046",
                    AlunoNome = "DANIEL MARQUES SANTOS",
                    AnoLetivo = 2022,
                    DreNome = "DRE-BT",
                    UeNome = "CEU EMEF BUTANTA",
                    TurmaNome = "EF-1A",
                    SituacaoPlano = "Validado",
                    VersaoPlano = "v2-21/10/2022"
                },
                Cadastro = new CadastroPlanoAeeDto()
                {
                    Responsavel = "TATIANE GONÇALVES FERREIRA SOARES (7951493)",
                    Questoes = new List<QuestaoPlanoAeeDto>()
                    {
                        new QuestaoPlanoAeeDto
                        {
                            Ordem = 1, Questao = "BIMESTRE DE VIGÊNCIA DO PLANO", Resposta = "4º BIMESTRE-2022",
                            TipoQuestao = TipoQuestao.PeriodoEscolar
                        },
                        new QuestaoPlanoAeeDto
                        {
                            Ordem = 2, Questao = "ORGANIZAÇÃO DO AEE", Resposta = "ITINERANTE",
                            TipoQuestao = TipoQuestao.Radio
                        },
                        new QuestaoPlanoAeeDto
                        {
                            Ordem = 3, Questao = "DIAS E HORÁRIOS DE FREQUÊNCIA DO ESTUDANTE NO AEE",
                            Resposta = "EM GRUPO", TipoQuestao = TipoQuestao.FrequenciaEstudanteAEE,
                            FrequenciaAluno = new List<FrequenciaAlunoDto>()
                            {
                                new FrequenciaAlunoDto()
                                    { DiaDaSemana = "SEGUNDA-FEIRA", Inicio = "08:00", Termino = "17:30" },
                                new FrequenciaAlunoDto()
                                    { DiaDaSemana = "TERÇA-FEIRA", Inicio = "09:00", Termino = "16:30" },
                                new FrequenciaAlunoDto()
                                    { DiaDaSemana = "QUARTA-FEIRA", Inicio = "10:00", Termino = "15:30" },
                                new FrequenciaAlunoDto()
                                    { DiaDaSemana = "QUINTA-FEIRA", Inicio = "11:00", Termino = "14:30" },
                                new FrequenciaAlunoDto()
                                    { DiaDaSemana = "SEXTA-FEIRA", Inicio = "08:00", Termino = "13:30" },
                                new FrequenciaAlunoDto()
                                    { DiaDaSemana = "SEXTA-FEIRA", Inicio = "14:00", Termino = "15:30" },
                                new FrequenciaAlunoDto()
                                    { DiaDaSemana = "SEXTA-FEIRA", Inicio = "16:00", Termino = "18:30" },

                            }
                        },
                        new QuestaoPlanoAeeDto
                        {
                            Ordem = 4, Questao = "FORMAS DE ATENDIMENTO EDUCACIONAL ESPECIALIZADO DO ESTUDANTE",
                            Resposta = "EM GRUPO", TipoQuestao = TipoQuestao.Radio,
                            Justificativa =
                                "JUSTIFICATIVA DE FORMAS DE ATENDIMENTO EDUCACIONAL ESPECIALIZADO DO ESTUDANTE - JUSTIFICATIVA DE FORMAS DE ATENDIMENTO EDUCACIONAL ESPECIALIZADO DO ESTUDANTE - JUSTIFICATIVA DE FORMAS DE ATENDIMENTO EDUCACIONAL ESPECIALIZADO DO ESTUDANTE - JUSTIFICATIVA DE FORMAS DE ATENDIMENTO EDUCACIONAL ESPECIALIZADO DO ESTUDANTE - JUSTIFICATIVA DE FORMAS DE ATENDIMENTO EDUCACIONAL ESPECIALIZADO DO ESTUDANTE - JUSTIFICATIVA DE FORMAS DE ATENDIMENTO EDUCACIONAL ESPECIALIZADO DO ESTUDANTE - JUSTIFICATIVA DE FORMAS DE ATENDIMENTO EDUCACIONAL ESPECIALIZADO DO ESTUDANTE - JUSTIFICATIVA DE FORMAS DE ATENDIMENTO EDUCACIONAL ESPECIALIZADO DO ESTUDANTE - JUSTIFICATIVA DE FORMAS DE ATENDIMENTO EDUCACIONAL ESPECIALIZADO DO ESTUDANTE - JUSTIFICATIVA DE FORMAS DE ATENDIMENTO EDUCACIONAL ESPECIALIZADO DO ESTUDANTE - JUSTIFICATIVA DE FORMAS DE ATENDIMENTO EDUCACIONAL ESPECIALIZADO DO ESTUDANTE - JUSTIFICATIVA DE FORMAS DE ATENDIMENTO EDUCACIONAL ESPECIALIZADO DO ESTUDANTE - JUSTIFICATIVA DE FORMAS DE ATENDIMENTO EDUCACIONAL ESPECIALIZADO DO ESTUDANTE - JUSTIFICATIVA DE FORMAS DE ATENDIMENTO EDUCACIONAL ESPECIALIZADO DO ESTUDANTE - "
                        },
                        new QuestaoPlanoAeeDto
                        {
                            Ordem = 5, Questao = "OBJETIVOS DO AEE",
                            Resposta =
                                "DESCRIÇÃO DOS OBJETIVOS DO AEE - DESCRIÇÃO DOS OBJETIVOS DO AEE - DESCRIÇÃO DOS OBJETIVOS DO AEE - DESCRIÇÃO DOS OBJETIVOS DO AEE - DESCRIÇÃO DOS OBJETIVOS DO AEE - DESCRIÇÃO DOS OBJETIVOS DO AEE - DESCRIÇÃO DOS OBJETIVOS DO AEE - DESCRIÇÃO DOS OBJETIVOS DO AEE - DESCRIÇÃO DOS OBJETIVOS DO AEE - DESCRIÇÃO DOS OBJETIVOS DO AEE - DESCRIÇÃO DOS OBJETIVOS DO AEE - DESCRIÇÃO DOS OBJETIVOS DO AEE - DESCRIÇÃO DOS OBJETIVOS DO AEE - DESCRIÇÃO DOS OBJETIVOS DO AEE - DESCRIÇÃO DOS OBJETIVOS DO AEE - DESCRIÇÃO DOS OBJETIVOS DO AEE - DESCRIÇÃO DOS OBJETIVOS DO AEE - DESCRIÇÃO DOS OBJETIVOS DO AEE - DESCRIÇÃO DOS OBJETIVOS DO AEE - DESCRIÇÃO DOS OBJETIVOS DO AEE - DESCRIÇÃO DOS OBJETIVOS DO AEE - DESCRIÇÃO DOS OBJETIVOS DO AEE - DESCRIÇÃO DOS OBJETIVOS DO AEE - DESCRIÇÃO DOS OBJETIVOS DO AEE - DESCRIÇÃO DOS OBJETIVOS DO AEE - DESCRIÇÃO DOS OBJETIVOS DO AEE - DESCRIÇÃO DOS OBJETIVOS DO AEE - DESCRIÇÃO DOS OBJETIVOS DO AEE - DESCRIÇÃO DOS OBJETIVOS DO AEE - DESCRIÇÃO DOS OBJETIVOS DO AEE - DESCRIÇÃO DOS OBJETIVOS DO AEE - DESCRIÇÃO DOS OBJETIVOS DO AEE - DESCRIÇÃO DOS OBJETIVOS DO AEE - DESCRIÇÃO DOS OBJETIVOS DO AEE - DESCRIÇÃO DOS OBJETIVOS DO AEE - DESCRIÇÃO DOS OBJETIVOS DO AEE - DESCRIÇÃO DOS OBJETIVOS DO AEE - ",
                            TipoQuestao = TipoQuestao.Texto
                        },
                        new QuestaoPlanoAeeDto
                        {
                            Ordem = 6, Questao = "ORIENTAÇÕES DE AÇÕES PARA O DESENVOLVIMENTO/ATIVIDADE DO AEE",
                            Resposta =
                                "DESCRIÇÃO DOS ORIENTAÇÕES DE AÇÕES PARA O DESENVOLVIMENTO/ATIVIDADE DO AEE - DESCRIÇÃO DOS ORIENTAÇÕES DE AÇÕES PARA O DESENVOLVIMENTO/ATIVIDADE DO AEE - DESCRIÇÃO DOS ORIENTAÇÕES DE AÇÕES PARA O DESENVOLVIMENTO/ATIVIDADE DO AEE - DESCRIÇÃO DOS ORIENTAÇÕES DE AÇÕES PARA O DESENVOLVIMENTO/ATIVIDADE DO AEE - DESCRIÇÃO DOS ORIENTAÇÕES DE AÇÕES PARA O DESENVOLVIMENTO/ATIVIDADE DO AEE - DESCRIÇÃO DOS ORIENTAÇÕES DE AÇÕES PARA O DESENVOLVIMENTO/ATIVIDADE DO AEE - DESCRIÇÃO DOS ORIENTAÇÕES DE AÇÕES PARA O DESENVOLVIMENTO/ATIVIDADE DO AEE - DESCRIÇÃO DOS ORIENTAÇÕES DE AÇÕES PARA O DESENVOLVIMENTO/ATIVIDADE DO AEE - DESCRIÇÃO DOS ORIENTAÇÕES DE AÇÕES PARA O DESENVOLVIMENTO/ATIVIDADE DO AEE - DESCRIÇÃO DOS ORIENTAÇÕES DE AÇÕES PARA O DESENVOLVIMENTO/ATIVIDADE DO AEE - DESCRIÇÃO DOS ORIENTAÇÕES DE AÇÕES PARA O DESENVOLVIMENTO/ATIVIDADE DO AEE - DESCRIÇÃO DOS ORIENTAÇÕES DE AÇÕES PARA O DESENVOLVIMENTO/ATIVIDADE DO AEE - DESCRIÇÃO DOS ORIENTAÇÕES DE AÇÕES PARA O DESENVOLVIMENTO/ATIVIDADE DO AEE - DESCRIÇÃO DOS ORIENTAÇÕES DE AÇÕES PARA O DESENVOLVIMENTO/ATIVIDADE DO AEE - DESCRIÇÃO DOS ORIENTAÇÕES DE AÇÕES PARA O DESENVOLVIMENTO/ATIVIDADE DO AEE - DESCRIÇÃO DOS ORIENTAÇÕES DE AÇÕES PARA O DESENVOLVIMENTO/ATIVIDADE DO AEE - DESCRIÇÃO DOS ORIENTAÇÕES DE AÇÕES PARA O DESENVOLVIMENTO/ATIVIDADE DO AEE - DESCRIÇÃO DOS ORIENTAÇÕES DE AÇÕES PARA O DESENVOLVIMENTO/ATIVIDADE DO AEE - ",
                            TipoQuestao = TipoQuestao.Texto
                        },
                        new QuestaoPlanoAeeDto
                        {
                            Ordem = 7,
                            Questao =
                                "TEM NECESSIDADE DE RECURSOS DE ACESSIBILIDADE/MATERIAIS PARA ELIMINAÇÃO DE BARREIRAS PARA A SALA REGULAR (SELEÇÃO DE MATERIAIS, EQUIPAMENTOS E MOBILIÁRIO)",
                            Resposta = "SIM", TipoQuestao = TipoQuestao.Radio,
                            Justificativa =
                                "DESCRIÇÃO DOS TEM NECESSIDADE DE RECURSOS DE ACESSIBILIDADE/MATERIAIS PARA ELIMINAÇÃO DE BARREIRAS PARA A SALA REGULAR (SELEÇÃO DE MATERIAIS, EQUIPAMENTOS E MOBILIÁRIO)"
                        },
                        new QuestaoPlanoAeeDto
                        {
                            Ordem = 8,
                            Questao =
                                "TEM NECESSIDADE DE RECURSOS DE ACESSIBILIDADE/MATERIAIS PARA ELIMINAÇÃO DE BARREIRAS PARA A SALA DE RECURSOS MULTIFUNCIONAIS (SELEÇÃO DE MATERIAIS, EQUIPAMENTOS E MOBILIÁRIO)",
                            Resposta = "SIM", TipoQuestao = TipoQuestao.Radio,
                            Justificativa =
                                "DESCRIÇÃO DOS TEM NECESSIDADE DE RECURSOS DE ACESSIBILIDADE/MATERIAIS PARA ELIMINAÇÃO DE BARREIRAS PARA A SALA DE RECURSOS MULTIFUNCIONAIS (SELEÇÃO DE MATERIAIS, EQUIPAMENTOS E MOBILIÁRIO) - DESCRIÇÃO DOS TEM NECESSIDADE DE RECURSOS DE ACESSIBILIDADE/MATERIAIS PARA ELIMINAÇÃO DE BARREIRAS PARA A SALA DE RECURSOS MULTIFUNCIONAIS (SELEÇÃO DE MATERIAIS, EQUIPAMENTOS E MOBILIÁRIO) - DESCRIÇÃO DOS TEM NECESSIDADE DE RECURSOS DE ACESSIBILIDADE/MATERIAIS PARA ELIMINAÇÃO DE BARREIRAS PARA A SALA DE RECURSOS MULTIFUNCIONAIS (SELEÇÃO DE MATERIAIS, EQUIPAMENTOS E MOBILIÁRIO) - DESCRIÇÃO DOS TEM NECESSIDADE DE RECURSOS DE ACESSIBILIDADE/MATERIAIS PARA ELIMINAÇÃO DE BARREIRAS PARA A SALA DE RECURSOS MULTIFUNCIONAIS (SELEÇÃO DE MATERIAIS, EQUIPAMENTOS E MOBILIÁRIO) - DESCRIÇÃO DOS TEM NECESSIDADE DE RECURSOS DE ACESSIBILIDADE/MATERIAIS PARA ELIMINAÇÃO DE BARREIRAS PARA A SALA DE RECURSOS MULTIFUNCIONAIS (SELEÇÃO DE MATERIAIS, EQUIPAMENTOS E MOBILIÁRIO) - DESCRIÇÃO DOS TEM NECESSIDADE DE RECURSOS DE ACESSIBILIDADE/MATERIAIS PARA ELIMINAÇÃO DE BARREIRAS PARA A SALA DE RECURSOS MULTIFUNCIONAIS (SELEÇÃO DE MATERIAIS, EQUIPAMENTOS E MOBILIÁRIO) - DESCRIÇÃO DOS TEM NECESSIDADE DE RECURSOS DE ACESSIBILIDADE/MATERIAIS PARA ELIMINAÇÃO DE BARREIRAS PARA A SALA DE RECURSOS MULTIFUNCIONAIS (SELEÇÃO DE MATERIAIS, EQUIPAMENTOS E MOBILIÁRIO) - DESCRIÇÃO DOS TEM NECESSIDADE DE RECURSOS DE ACESSIBILIDADE/MATERIAIS PARA ELIMINAÇÃO DE BARREIRAS PARA A SALA DE RECURSOS MULTIFUNCIONAIS (SELEÇÃO DE MATERIAIS, EQUIPAMENTOS E MOBILIÁRIO) - DESCRIÇÃO DOS TEM NECESSIDADE DE RECURSOS DE ACESSIBILIDADE/MATERIAIS PARA ELIMINAÇÃO DE BARREIRAS PARA A SALA DE RECURSOS MULTIFUNCIONAIS (SELEÇÃO DE MATERIAIS, EQUIPAMENTOS E MOBILIÁRIO) - DESCRIÇÃO DOS TEM NECESSIDADE DE RECURSOS DE ACESSIBILIDADE/MATERIAIS PARA ELIMINAÇÃO DE BARREIRAS PARA A SALA DE RECURSOS MULTIFUNCIONAIS (SELEÇÃO DE MATERIAIS, EQUIPAMENTOS E MOBILIÁRIO) - DESCRIÇÃO DOS TEM NECESSIDADE DE RECURSOS DE ACESSIBILIDADE/MATERIAIS PARA ELIMINAÇÃO DE BARREIRAS PARA A SALA DE RECURSOS MULTIFUNCIONAIS (SELEÇÃO DE MATERIAIS, EQUIPAMENTOS E MOBILIÁRIO) - DESCRIÇÃO DOS TEM NECESSIDADE DE RECURSOS DE ACESSIBILIDADE/MATERIAIS PARA ELIMINAÇÃO DE BARREIRAS PARA A SALA DE RECURSOS MULTIFUNCIONAIS (SELEÇÃO DE MATERIAIS, EQUIPAMENTOS E MOBILIÁRIO) - DESCRIÇÃO DOS TEM NECESSIDADE DE RECURSOS DE ACESSIBILIDADE/MATERIAIS PARA ELIMINAÇÃO DE BARREIRAS PARA A SALA DE RECURSOS MULTIFUNCIONAIS (SELEÇÃO DE MATERIAIS, EQUIPAMENTOS E MOBILIÁRIO) - DESCRIÇÃO DOS TEM NECESSIDADE DE RECURSOS DE ACESSIBILIDADE/MATERIAIS PARA ELIMINAÇÃO DE BARREIRAS PARA A SALA DE RECURSOS MULTIFUNCIONAIS (SELEÇÃO DE MATERIAIS, EQUIPAMENTOS E MOBILIÁRIO) - DESCRIÇÃO DOS TEM NECESSIDADE DE RECURSOS DE ACESSIBILIDADE/MATERIAIS PARA ELIMINAÇÃO DE BARREIRAS PARA A SALA DE RECURSOS MULTIFUNCIONAIS (SELEÇÃO DE MATERIAIS, EQUIPAMENTOS E MOBILIÁRIO) - DESCRIÇÃO DOS TEM NECESSIDADE DE RECURSOS DE ACESSIBILIDADE/MATERIAIS PARA ELIMINAÇÃO DE BARREIRAS PARA A SALA DE RECURSOS MULTIFUNCIONAIS (SELEÇÃO DE MATERIAIS, EQUIPAMENTOS E MOBILIÁRIO) - "
                        },
                        new QuestaoPlanoAeeDto
                        {
                            Ordem = 9,
                            Questao = "MOBILIZAÇÃO DOS RECURSOS HUMANOS DA U.E. OU PARCERIAS NA UNIDADE EDUCACIONAL",
                            Resposta = "SIM", TipoQuestao = TipoQuestao.Radio,
                            Justificativa =
                                "DESCRIÇÃO DOS MOBILIZAÇÃO DOS RECURSOS HUMANOS DA U.E. OU PARCERIAS NA UNIDADE EDUCACIONAL"
                        },
                        new QuestaoPlanoAeeDto
                        {
                            Ordem = 10,
                            Questao =
                                "MOBILIZAÇÃO DOS RECURSOS HUMANOS COM PROFISSIONAIS EXTERNOS À UNIDADE EDUCACIONAL",
                            Resposta = "SIM", TipoQuestao = TipoQuestao.Radio,
                            Justificativa =
                                "DESCRIÇÃO DOS MOBILIZAÇÃO DOS RECURSOS HUMANOS COM PROFISSIONAIS EXTERNOS À UNIDADE EDUCACIONAL"
                        },
                    }
                },
                Parecer = new ParecerPlanoAeeDto()
                {
                    Coordenacao = "DESCRIÇÃO DO PARECER DA COORDENAÇÃO",
                    Cefai = "DESCRIÇÃO DO CEFAI",
                    PaaiResponsavel = "THAYA DE FATIMA BOTELHO (7762577)"
                }
            });
            
            relatorios.Add(new RelatorioPlanoAeeDto()
            {
                Cabecalho = new CabecalhoPlanoAeeDto()
                {
                    AlunoCodigo = "5187151",
                    AlunoNome = "ANA CAROLINA CECCARELLI BOBADILHA",
                    AnoLetivo = 2022,
                    DreNome = "DRE-BT",
                    UeNome = "CEU EMEF BUTANTA",
                    TurmaNome = "EF-1A",
                    SituacaoPlano = "Aguardando parecer do CEFAI",
                    VersaoPlano = "v2-21/10/2022"
                },
                Cadastro = new CadastroPlanoAeeDto()
                {
                    Responsavel = "ADALGISA GONCALVES (6769195)",
                    Questoes = new List<QuestaoPlanoAeeDto>()
                    {
                        new QuestaoPlanoAeeDto
                        {
                            Ordem = 1, Questao = "BIMESTRE DE VIGÊNCIA DO PLANO", Resposta = "4º BIMESTRE-2022",
                            TipoQuestao = TipoQuestao.PeriodoEscolar
                        },
                        new QuestaoPlanoAeeDto
                        {
                            Ordem = 2, Questao = "ORGANIZAÇÃO DO AEE", Resposta = "ITINERANTE",
                            TipoQuestao = TipoQuestao.Radio
                        },
                        new QuestaoPlanoAeeDto
                        {
                            Ordem = 3, Questao = "DIAS E HORÁRIOS DE FREQUÊNCIA DO ESTUDANTE NO AEE",
                            Resposta = "EM GRUPO", TipoQuestao = TipoQuestao.FrequenciaEstudanteAEE,
                            FrequenciaAluno = new List<FrequenciaAlunoDto>()
                            {
                                new FrequenciaAlunoDto()
                                    { DiaDaSemana = "SEGUNDA-FEIRA", Inicio = "08:00", Termino = "17:30" },
                                new FrequenciaAlunoDto()
                                    { DiaDaSemana = "TERÇA-FEIRA", Inicio = "09:00", Termino = "16:30" },
                            }
                        },
                        new QuestaoPlanoAeeDto
                        {
                            Ordem = 4, Questao = "FORMAS DE ATENDIMENTO EDUCACIONAL ESPECIALIZADO DO ESTUDANTE",
                            Resposta = "EM GRUPO", TipoQuestao = TipoQuestao.Radio,
                            Justificativa =
                                "JUSTIFICATIVA DE FORMAS DE ATENDIMENTO EDUCACIONAL ESPECIALIZADO DO ESTUDANTE - JUSTIFICATIVA DE FORMAS DE ATENDIMENTO EDUCACIONAL ESPECIALIZADO DO ESTUDANTE - JUSTIFICATIVA DE FORMAS DE ATENDIMENTO EDUCACIONAL ESPECIALIZADO DO ESTUDANTE - JUSTIFICATIVA DE FORMAS DE ATENDIMENTO EDUCACIONAL ESPECIALIZADO DO ESTUDANTE - JUSTIFICATIVA DE FORMAS DE ATENDIMENTO EDUCACIONAL ESPECIALIZADO DO ESTUDANTE - JUSTIFICATIVA DE FORMAS DE ATENDIMENTO EDUCACIONAL ESPECIALIZADO DO ESTUDANTE - JUSTIFICATIVA DE FORMAS DE ATENDIMENTO EDUCACIONAL ESPECIALIZADO DO ESTUDANTE - JUSTIFICATIVA DE FORMAS DE ATENDIMENTO EDUCACIONAL ESPECIALIZADO DO ESTUDANTE - JUSTIFICATIVA DE FORMAS DE ATENDIMENTO EDUCACIONAL ESPECIALIZADO DO ESTUDANTE - JUSTIFICATIVA DE FORMAS DE ATENDIMENTO EDUCACIONAL ESPECIALIZADO DO ESTUDANTE - JUSTIFICATIVA DE FORMAS DE ATENDIMENTO EDUCACIONAL ESPECIALIZADO DO ESTUDANTE - JUSTIFICATIVA DE FORMAS DE ATENDIMENTO EDUCACIONAL ESPECIALIZADO DO ESTUDANTE - JUSTIFICATIVA DE FORMAS DE ATENDIMENTO EDUCACIONAL ESPECIALIZADO DO ESTUDANTE - JUSTIFICATIVA DE FORMAS DE ATENDIMENTO EDUCACIONAL ESPECIALIZADO DO ESTUDANTE - "
                        },
                        new QuestaoPlanoAeeDto
                        {
                            Ordem = 5, Questao = "OBJETIVOS DO AEE",
                            Resposta =
                                "DESCRIÇÃO DOS OBJETIVOS DO AEE - DESCRIÇÃO DOS OBJETIVOS DO AEE - DESCRIÇÃO DOS OBJETIVOS DO AEE - DESCRIÇÃO DOS OBJETIVOS DO AEE - DESCRIÇÃO DOS OBJETIVOS DO AEE - DESCRIÇÃO DOS OBJETIVOS DO AEE - DESCRIÇÃO DOS OBJETIVOS DO AEE - DESCRIÇÃO DOS OBJETIVOS DO AEE - DESCRIÇÃO DOS OBJETIVOS DO AEE - DESCRIÇÃO DOS OBJETIVOS DO AEE - DESCRIÇÃO DOS OBJETIVOS DO AEE - DESCRIÇÃO DOS OBJETIVOS DO AEE - DESCRIÇÃO DOS OBJETIVOS DO AEE - DESCRIÇÃO DOS OBJETIVOS DO AEE - DESCRIÇÃO DOS OBJETIVOS DO AEE - DESCRIÇÃO DOS OBJETIVOS DO AEE - DESCRIÇÃO DOS OBJETIVOS DO AEE - DESCRIÇÃO DOS OBJETIVOS DO AEE - DESCRIÇÃO DOS OBJETIVOS DO AEE - DESCRIÇÃO DOS OBJETIVOS DO AEE - DESCRIÇÃO DOS OBJETIVOS DO AEE - DESCRIÇÃO DOS OBJETIVOS DO AEE - DESCRIÇÃO DOS OBJETIVOS DO AEE - DESCRIÇÃO DOS OBJETIVOS DO AEE - DESCRIÇÃO DOS OBJETIVOS DO AEE - DESCRIÇÃO DOS OBJETIVOS DO AEE - DESCRIÇÃO DOS OBJETIVOS DO AEE - DESCRIÇÃO DOS OBJETIVOS DO AEE - DESCRIÇÃO DOS OBJETIVOS DO AEE - DESCRIÇÃO DOS OBJETIVOS DO AEE - DESCRIÇÃO DOS OBJETIVOS DO AEE - DESCRIÇÃO DOS OBJETIVOS DO AEE - DESCRIÇÃO DOS OBJETIVOS DO AEE - DESCRIÇÃO DOS OBJETIVOS DO AEE - DESCRIÇÃO DOS OBJETIVOS DO AEE - DESCRIÇÃO DOS OBJETIVOS DO AEE - DESCRIÇÃO DOS OBJETIVOS DO AEE - ",
                            TipoQuestao = TipoQuestao.Texto
                        },
                        new QuestaoPlanoAeeDto
                        {
                            Ordem = 6, Questao = "ORIENTAÇÕES DE AÇÕES PARA O DESENVOLVIMENTO/ATIVIDADE DO AEE",
                            Resposta =
                                "DESCRIÇÃO DOS ORIENTAÇÕES DE AÇÕES PARA O DESENVOLVIMENTO/ATIVIDADE DO AEE - DESCRIÇÃO DOS ORIENTAÇÕES DE AÇÕES PARA O DESENVOLVIMENTO/ATIVIDADE DO AEE - DESCRIÇÃO DOS ORIENTAÇÕES DE AÇÕES PARA O DESENVOLVIMENTO/ATIVIDADE DO AEE - DESCRIÇÃO DOS ORIENTAÇÕES DE AÇÕES PARA O DESENVOLVIMENTO/ATIVIDADE DO AEE - DESCRIÇÃO DOS ORIENTAÇÕES DE AÇÕES PARA O DESENVOLVIMENTO/ATIVIDADE DO AEE - DESCRIÇÃO DOS ORIENTAÇÕES DE AÇÕES PARA O DESENVOLVIMENTO/ATIVIDADE DO AEE - DESCRIÇÃO DOS ORIENTAÇÕES DE AÇÕES PARA O DESENVOLVIMENTO/ATIVIDADE DO AEE - DESCRIÇÃO DOS ORIENTAÇÕES DE AÇÕES PARA O DESENVOLVIMENTO/ATIVIDADE DO AEE - DESCRIÇÃO DOS ORIENTAÇÕES DE AÇÕES PARA O DESENVOLVIMENTO/ATIVIDADE DO AEE - DESCRIÇÃO DOS ORIENTAÇÕES DE AÇÕES PARA O DESENVOLVIMENTO/ATIVIDADE DO AEE - DESCRIÇÃO DOS ORIENTAÇÕES DE AÇÕES PARA O DESENVOLVIMENTO/ATIVIDADE DO AEE - DESCRIÇÃO DOS ORIENTAÇÕES DE AÇÕES PARA O DESENVOLVIMENTO/ATIVIDADE DO AEE - DESCRIÇÃO DOS ORIENTAÇÕES DE AÇÕES PARA O DESENVOLVIMENTO/ATIVIDADE DO AEE - DESCRIÇÃO DOS ORIENTAÇÕES DE AÇÕES PARA O DESENVOLVIMENTO/ATIVIDADE DO AEE - DESCRIÇÃO DOS ORIENTAÇÕES DE AÇÕES PARA O DESENVOLVIMENTO/ATIVIDADE DO AEE - DESCRIÇÃO DOS ORIENTAÇÕES DE AÇÕES PARA O DESENVOLVIMENTO/ATIVIDADE DO AEE - DESCRIÇÃO DOS ORIENTAÇÕES DE AÇÕES PARA O DESENVOLVIMENTO/ATIVIDADE DO AEE - DESCRIÇÃO DOS ORIENTAÇÕES DE AÇÕES PARA O DESENVOLVIMENTO/ATIVIDADE DO AEE - ",
                            TipoQuestao = TipoQuestao.Texto
                        },
                        new QuestaoPlanoAeeDto
                        {
                            Ordem = 7,
                            Questao =
                                "TEM NECESSIDADE DE RECURSOS DE ACESSIBILIDADE/MATERIAIS PARA ELIMINAÇÃO DE BARREIRAS PARA A SALA REGULAR (SELEÇÃO DE MATERIAIS, EQUIPAMENTOS E MOBILIÁRIO)",
                            Resposta = "SIM", TipoQuestao = TipoQuestao.Radio,
                            Justificativa =
                                "DESCRIÇÃO DOS TEM NECESSIDADE DE RECURSOS DE ACESSIBILIDADE/MATERIAIS PARA ELIMINAÇÃO DE BARREIRAS PARA A SALA REGULAR (SELEÇÃO DE MATERIAIS, EQUIPAMENTOS E MOBILIÁRIO)"
                        },
                        new QuestaoPlanoAeeDto
                        {
                            Ordem = 8,
                            Questao =
                                "TEM NECESSIDADE DE RECURSOS DE ACESSIBILIDADE/MATERIAIS PARA ELIMINAÇÃO DE BARREIRAS PARA A SALA DE RECURSOS MULTIFUNCIONAIS (SELEÇÃO DE MATERIAIS, EQUIPAMENTOS E MOBILIÁRIO)",
                            Resposta = "SIM", TipoQuestao = TipoQuestao.Radio,
                            Justificativa =
                                "DESCRIÇÃO DOS TEM NECESSIDADE DE RECURSOS DE ACESSIBILIDADE/MATERIAIS PARA ELIMINAÇÃO DE BARREIRAS PARA A SALA DE RECURSOS MULTIFUNCIONAIS (SELEÇÃO DE MATERIAIS, EQUIPAMENTOS E MOBILIÁRIO) - DESCRIÇÃO DOS TEM NECESSIDADE DE RECURSOS DE ACESSIBILIDADE/MATERIAIS PARA ELIMINAÇÃO DE BARREIRAS PARA A SALA DE RECURSOS MULTIFUNCIONAIS (SELEÇÃO DE MATERIAIS, EQUIPAMENTOS E MOBILIÁRIO) - DESCRIÇÃO DOS TEM NECESSIDADE DE RECURSOS DE ACESSIBILIDADE/MATERIAIS PARA ELIMINAÇÃO DE BARREIRAS PARA A SALA DE RECURSOS MULTIFUNCIONAIS (SELEÇÃO DE MATERIAIS, EQUIPAMENTOS E MOBILIÁRIO) - DESCRIÇÃO DOS TEM NECESSIDADE DE RECURSOS DE ACESSIBILIDADE/MATERIAIS PARA ELIMINAÇÃO DE BARREIRAS PARA A SALA DE RECURSOS MULTIFUNCIONAIS (SELEÇÃO DE MATERIAIS, EQUIPAMENTOS E MOBILIÁRIO) - DESCRIÇÃO DOS TEM NECESSIDADE DE RECURSOS DE ACESSIBILIDADE/MATERIAIS PARA ELIMINAÇÃO DE BARREIRAS PARA A SALA DE RECURSOS MULTIFUNCIONAIS (SELEÇÃO DE MATERIAIS, EQUIPAMENTOS E MOBILIÁRIO) - DESCRIÇÃO DOS TEM NECESSIDADE DE RECURSOS DE ACESSIBILIDADE/MATERIAIS PARA ELIMINAÇÃO DE BARREIRAS PARA A SALA DE RECURSOS MULTIFUNCIONAIS (SELEÇÃO DE MATERIAIS, EQUIPAMENTOS E MOBILIÁRIO) - DESCRIÇÃO DOS TEM NECESSIDADE DE RECURSOS DE ACESSIBILIDADE/MATERIAIS PARA ELIMINAÇÃO DE BARREIRAS PARA A SALA DE RECURSOS MULTIFUNCIONAIS (SELEÇÃO DE MATERIAIS, EQUIPAMENTOS E MOBILIÁRIO) - DESCRIÇÃO DOS TEM NECESSIDADE DE RECURSOS DE ACESSIBILIDADE/MATERIAIS PARA ELIMINAÇÃO DE BARREIRAS PARA A SALA DE RECURSOS MULTIFUNCIONAIS (SELEÇÃO DE MATERIAIS, EQUIPAMENTOS E MOBILIÁRIO) - DESCRIÇÃO DOS TEM NECESSIDADE DE RECURSOS DE ACESSIBILIDADE/MATERIAIS PARA ELIMINAÇÃO DE BARREIRAS PARA A SALA DE RECURSOS MULTIFUNCIONAIS (SELEÇÃO DE MATERIAIS, EQUIPAMENTOS E MOBILIÁRIO) - DESCRIÇÃO DOS TEM NECESSIDADE DE RECURSOS DE ACESSIBILIDADE/MATERIAIS PARA ELIMINAÇÃO DE BARREIRAS PARA A SALA DE RECURSOS MULTIFUNCIONAIS (SELEÇÃO DE MATERIAIS, EQUIPAMENTOS E MOBILIÁRIO) - DESCRIÇÃO DOS TEM NECESSIDADE DE RECURSOS DE ACESSIBILIDADE/MATERIAIS PARA ELIMINAÇÃO DE BARREIRAS PARA A SALA DE RECURSOS MULTIFUNCIONAIS (SELEÇÃO DE MATERIAIS, EQUIPAMENTOS E MOBILIÁRIO) - DESCRIÇÃO DOS TEM NECESSIDADE DE RECURSOS DE ACESSIBILIDADE/MATERIAIS PARA ELIMINAÇÃO DE BARREIRAS PARA A SALA DE RECURSOS MULTIFUNCIONAIS (SELEÇÃO DE MATERIAIS, EQUIPAMENTOS E MOBILIÁRIO) - DESCRIÇÃO DOS TEM NECESSIDADE DE RECURSOS DE ACESSIBILIDADE/MATERIAIS PARA ELIMINAÇÃO DE BARREIRAS PARA A SALA DE RECURSOS MULTIFUNCIONAIS (SELEÇÃO DE MATERIAIS, EQUIPAMENTOS E MOBILIÁRIO) - DESCRIÇÃO DOS TEM NECESSIDADE DE RECURSOS DE ACESSIBILIDADE/MATERIAIS PARA ELIMINAÇÃO DE BARREIRAS PARA A SALA DE RECURSOS MULTIFUNCIONAIS (SELEÇÃO DE MATERIAIS, EQUIPAMENTOS E MOBILIÁRIO) - DESCRIÇÃO DOS TEM NECESSIDADE DE RECURSOS DE ACESSIBILIDADE/MATERIAIS PARA ELIMINAÇÃO DE BARREIRAS PARA A SALA DE RECURSOS MULTIFUNCIONAIS (SELEÇÃO DE MATERIAIS, EQUIPAMENTOS E MOBILIÁRIO) - DESCRIÇÃO DOS TEM NECESSIDADE DE RECURSOS DE ACESSIBILIDADE/MATERIAIS PARA ELIMINAÇÃO DE BARREIRAS PARA A SALA DE RECURSOS MULTIFUNCIONAIS (SELEÇÃO DE MATERIAIS, EQUIPAMENTOS E MOBILIÁRIO) - "
                        },
                        new QuestaoPlanoAeeDto
                        {
                            Ordem = 9,
                            Questao = "MOBILIZAÇÃO DOS RECURSOS HUMANOS DA U.E. OU PARCERIAS NA UNIDADE EDUCACIONAL",
                            Resposta = "SIM", TipoQuestao = TipoQuestao.Radio,
                            Justificativa =
                                "DESCRIÇÃO DOS MOBILIZAÇÃO DOS RECURSOS HUMANOS DA U.E. OU PARCERIAS NA UNIDADE EDUCACIONAL"
                        },
                        new QuestaoPlanoAeeDto
                        {
                            Ordem = 10,
                            Questao =
                                "MOBILIZAÇÃO DOS RECURSOS HUMANOS COM PROFISSIONAIS EXTERNOS À UNIDADE EDUCACIONAL",
                            Resposta = "SIM", TipoQuestao = TipoQuestao.Radio,
                            Justificativa =
                                "DESCRIÇÃO DOS MOBILIZAÇÃO DOS RECURSOS HUMANOS COM PROFISSIONAIS EXTERNOS À UNIDADE EDUCACIONAL"
                        },
                    }
                },
                Parecer = new ParecerPlanoAeeDto()
                {
                    Coordenacao = "DESCRIÇÃO DO PARECER DA COORDENAÇÃO",
                    
                }
            });    
            
            relatorios.Add(new RelatorioPlanoAeeDto()
            {
                Cabecalho = new CabecalhoPlanoAeeDto()
                {
                    AlunoCodigo = "5581822",
                    AlunoNome = "CARLOS GABRIEL DOS SANTOS SILVA",
                    AnoLetivo = 2022,
                    DreNome = "DRE-BT",
                    UeNome = "CEU EMEF BUTANTA",
                    TurmaNome = "EF-1A",
                    SituacaoPlano = "Aguardando parecer da coordenação",
                    VersaoPlano = "v2-21/10/2022"
                },
                Cadastro = new CadastroPlanoAeeDto()
                {
                    Responsavel = "TATIANE GONÇALVES FERREIRA SOARES (7951493)",
                    Questoes = new List<QuestaoPlanoAeeDto>()
                    {
                        new QuestaoPlanoAeeDto
                        {
                            Ordem = 1, Questao = "BIMESTRE DE VIGÊNCIA DO PLANO", Resposta = "4º BIMESTRE-2022",
                            TipoQuestao = TipoQuestao.PeriodoEscolar
                        },
                        new QuestaoPlanoAeeDto
                        {
                            Ordem = 2, Questao = "ORGANIZAÇÃO DO AEE", Resposta = "ITINERANTE",
                            TipoQuestao = TipoQuestao.Radio
                        },
                        new QuestaoPlanoAeeDto
                        {
                            Ordem = 3, Questao = "DIAS E HORÁRIOS DE FREQUÊNCIA DO ESTUDANTE NO AEE",
                            Resposta = "EM GRUPO", TipoQuestao = TipoQuestao.FrequenciaEstudanteAEE,
                            FrequenciaAluno = new List<FrequenciaAlunoDto>()
                            {
                                new FrequenciaAlunoDto()
                                    { DiaDaSemana = "SEGUNDA-FEIRA", Inicio = "08:00", Termino = "17:30" },
                                new FrequenciaAlunoDto()
                                    { DiaDaSemana = "TERÇA-FEIRA", Inicio = "09:00", Termino = "16:30" },
                                new FrequenciaAlunoDto()
                                    { DiaDaSemana = "QUARTA-FEIRA", Inicio = "10:00", Termino = "15:30" },
                                new FrequenciaAlunoDto()
                                    { DiaDaSemana = "QUINTA-FEIRA", Inicio = "11:00", Termino = "14:30" },
                                new FrequenciaAlunoDto()
                                    { DiaDaSemana = "SEXTA-FEIRA", Inicio = "08:00", Termino = "13:30" },
                            }
                        },
                        new QuestaoPlanoAeeDto
                        {
                            Ordem = 4, Questao = "FORMAS DE ATENDIMENTO EDUCACIONAL ESPECIALIZADO DO ESTUDANTE",
                            Resposta = "EM GRUPO", TipoQuestao = TipoQuestao.Radio,
                            Justificativa =
                                "JUSTIFICATIVA DE FORMAS DE ATENDIMENTO EDUCACIONAL ESPECIALIZADO DO ESTUDANTE - JUSTIFICATIVA DE FORMAS DE ATENDIMENTO EDUCACIONAL ESPECIALIZADO DO ESTUDANTE - JUSTIFICATIVA DE FORMAS DE ATENDIMENTO EDUCACIONAL ESPECIALIZADO DO ESTUDANTE - JUSTIFICATIVA DE FORMAS DE ATENDIMENTO EDUCACIONAL ESPECIALIZADO DO ESTUDANTE - JUSTIFICATIVA DE FORMAS DE ATENDIMENTO EDUCACIONAL ESPECIALIZADO DO ESTUDANTE - JUSTIFICATIVA DE FORMAS DE ATENDIMENTO EDUCACIONAL ESPECIALIZADO DO ESTUDANTE - JUSTIFICATIVA DE FORMAS DE ATENDIMENTO EDUCACIONAL ESPECIALIZADO DO ESTUDANTE - JUSTIFICATIVA DE FORMAS DE ATENDIMENTO EDUCACIONAL ESPECIALIZADO DO ESTUDANTE - JUSTIFICATIVA DE FORMAS DE ATENDIMENTO EDUCACIONAL ESPECIALIZADO DO ESTUDANTE - JUSTIFICATIVA DE FORMAS DE ATENDIMENTO EDUCACIONAL ESPECIALIZADO DO ESTUDANTE - JUSTIFICATIVA DE FORMAS DE ATENDIMENTO EDUCACIONAL ESPECIALIZADO DO ESTUDANTE - JUSTIFICATIVA DE FORMAS DE ATENDIMENTO EDUCACIONAL ESPECIALIZADO DO ESTUDANTE - JUSTIFICATIVA DE FORMAS DE ATENDIMENTO EDUCACIONAL ESPECIALIZADO DO ESTUDANTE - JUSTIFICATIVA DE FORMAS DE ATENDIMENTO EDUCACIONAL ESPECIALIZADO DO ESTUDANTE - "
                        },
                        new QuestaoPlanoAeeDto
                        {
                            Ordem = 5, Questao = "OBJETIVOS DO AEE",
                            Resposta =
                                "DESCRIÇÃO DOS OBJETIVOS DO AEE - DESCRIÇÃO DOS OBJETIVOS DO AEE - DESCRIÇÃO DOS OBJETIVOS DO AEE - DESCRIÇÃO DOS OBJETIVOS DO AEE - DESCRIÇÃO DOS OBJETIVOS DO AEE - DESCRIÇÃO DOS OBJETIVOS DO AEE - DESCRIÇÃO DOS OBJETIVOS DO AEE - DESCRIÇÃO DOS OBJETIVOS DO AEE - DESCRIÇÃO DOS OBJETIVOS DO AEE - DESCRIÇÃO DOS OBJETIVOS DO AEE - DESCRIÇÃO DOS OBJETIVOS DO AEE - DESCRIÇÃO DOS OBJETIVOS DO AEE - DESCRIÇÃO DOS OBJETIVOS DO AEE - DESCRIÇÃO DOS OBJETIVOS DO AEE - DESCRIÇÃO DOS OBJETIVOS DO AEE - DESCRIÇÃO DOS OBJETIVOS DO AEE - DESCRIÇÃO DOS OBJETIVOS DO AEE - DESCRIÇÃO DOS OBJETIVOS DO AEE - DESCRIÇÃO DOS OBJETIVOS DO AEE - DESCRIÇÃO DOS OBJETIVOS DO AEE - DESCRIÇÃO DOS OBJETIVOS DO AEE - DESCRIÇÃO DOS OBJETIVOS DO AEE - DESCRIÇÃO DOS OBJETIVOS DO AEE - DESCRIÇÃO DOS OBJETIVOS DO AEE - DESCRIÇÃO DOS OBJETIVOS DO AEE - DESCRIÇÃO DOS OBJETIVOS DO AEE - DESCRIÇÃO DOS OBJETIVOS DO AEE - DESCRIÇÃO DOS OBJETIVOS DO AEE - DESCRIÇÃO DOS OBJETIVOS DO AEE - DESCRIÇÃO DOS OBJETIVOS DO AEE - DESCRIÇÃO DOS OBJETIVOS DO AEE - DESCRIÇÃO DOS OBJETIVOS DO AEE - DESCRIÇÃO DOS OBJETIVOS DO AEE - DESCRIÇÃO DOS OBJETIVOS DO AEE - DESCRIÇÃO DOS OBJETIVOS DO AEE - DESCRIÇÃO DOS OBJETIVOS DO AEE - DESCRIÇÃO DOS OBJETIVOS DO AEE - ",
                            TipoQuestao = TipoQuestao.Texto
                        },
                        new QuestaoPlanoAeeDto
                        {
                            Ordem = 6, Questao = "ORIENTAÇÕES DE AÇÕES PARA O DESENVOLVIMENTO/ATIVIDADE DO AEE",
                            Resposta =
                                "DESCRIÇÃO DOS ORIENTAÇÕES DE AÇÕES PARA O DESENVOLVIMENTO/ATIVIDADE DO AEE - DESCRIÇÃO DOS ORIENTAÇÕES DE AÇÕES PARA O DESENVOLVIMENTO/ATIVIDADE DO AEE - DESCRIÇÃO DOS ORIENTAÇÕES DE AÇÕES PARA O DESENVOLVIMENTO/ATIVIDADE DO AEE - DESCRIÇÃO DOS ORIENTAÇÕES DE AÇÕES PARA O DESENVOLVIMENTO/ATIVIDADE DO AEE - DESCRIÇÃO DOS ORIENTAÇÕES DE AÇÕES PARA O DESENVOLVIMENTO/ATIVIDADE DO AEE - DESCRIÇÃO DOS ORIENTAÇÕES DE AÇÕES PARA O DESENVOLVIMENTO/ATIVIDADE DO AEE - DESCRIÇÃO DOS ORIENTAÇÕES DE AÇÕES PARA O DESENVOLVIMENTO/ATIVIDADE DO AEE - DESCRIÇÃO DOS ORIENTAÇÕES DE AÇÕES PARA O DESENVOLVIMENTO/ATIVIDADE DO AEE - DESCRIÇÃO DOS ORIENTAÇÕES DE AÇÕES PARA O DESENVOLVIMENTO/ATIVIDADE DO AEE - DESCRIÇÃO DOS ORIENTAÇÕES DE AÇÕES PARA O DESENVOLVIMENTO/ATIVIDADE DO AEE - DESCRIÇÃO DOS ORIENTAÇÕES DE AÇÕES PARA O DESENVOLVIMENTO/ATIVIDADE DO AEE - DESCRIÇÃO DOS ORIENTAÇÕES DE AÇÕES PARA O DESENVOLVIMENTO/ATIVIDADE DO AEE - DESCRIÇÃO DOS ORIENTAÇÕES DE AÇÕES PARA O DESENVOLVIMENTO/ATIVIDADE DO AEE - DESCRIÇÃO DOS ORIENTAÇÕES DE AÇÕES PARA O DESENVOLVIMENTO/ATIVIDADE DO AEE - DESCRIÇÃO DOS ORIENTAÇÕES DE AÇÕES PARA O DESENVOLVIMENTO/ATIVIDADE DO AEE - DESCRIÇÃO DOS ORIENTAÇÕES DE AÇÕES PARA O DESENVOLVIMENTO/ATIVIDADE DO AEE - DESCRIÇÃO DOS ORIENTAÇÕES DE AÇÕES PARA O DESENVOLVIMENTO/ATIVIDADE DO AEE - DESCRIÇÃO DOS ORIENTAÇÕES DE AÇÕES PARA O DESENVOLVIMENTO/ATIVIDADE DO AEE - ",
                            TipoQuestao = TipoQuestao.Texto
                        },
                        new QuestaoPlanoAeeDto
                        {
                            Ordem = 7,
                            Questao =
                                "TEM NECESSIDADE DE RECURSOS DE ACESSIBILIDADE/MATERIAIS PARA ELIMINAÇÃO DE BARREIRAS PARA A SALA REGULAR (SELEÇÃO DE MATERIAIS, EQUIPAMENTOS E MOBILIÁRIO)",
                            Resposta = "SIM", TipoQuestao = TipoQuestao.Radio,
                            Justificativa =
                                "DESCRIÇÃO DOS TEM NECESSIDADE DE RECURSOS DE ACESSIBILIDADE/MATERIAIS PARA ELIMINAÇÃO DE BARREIRAS PARA A SALA REGULAR (SELEÇÃO DE MATERIAIS, EQUIPAMENTOS E MOBILIÁRIO)"
                        },
                        new QuestaoPlanoAeeDto
                        {
                            Ordem = 8,
                            Questao =
                                "TEM NECESSIDADE DE RECURSOS DE ACESSIBILIDADE/MATERIAIS PARA ELIMINAÇÃO DE BARREIRAS PARA A SALA DE RECURSOS MULTIFUNCIONAIS (SELEÇÃO DE MATERIAIS, EQUIPAMENTOS E MOBILIÁRIO)",
                            Resposta = "SIM", TipoQuestao = TipoQuestao.Radio,
                            Justificativa =
                                "DESCRIÇÃO DOS TEM NECESSIDADE DE RECURSOS DE ACESSIBILIDADE/MATERIAIS PARA ELIMINAÇÃO DE BARREIRAS PARA A SALA DE RECURSOS MULTIFUNCIONAIS (SELEÇÃO DE MATERIAIS, EQUIPAMENTOS E MOBILIÁRIO) - DESCRIÇÃO DOS TEM NECESSIDADE DE RECURSOS DE ACESSIBILIDADE/MATERIAIS PARA ELIMINAÇÃO DE BARREIRAS PARA A SALA DE RECURSOS MULTIFUNCIONAIS (SELEÇÃO DE MATERIAIS, EQUIPAMENTOS E MOBILIÁRIO) - DESCRIÇÃO DOS TEM NECESSIDADE DE RECURSOS DE ACESSIBILIDADE/MATERIAIS PARA ELIMINAÇÃO DE BARREIRAS PARA A SALA DE RECURSOS MULTIFUNCIONAIS (SELEÇÃO DE MATERIAIS, EQUIPAMENTOS E MOBILIÁRIO) - DESCRIÇÃO DOS TEM NECESSIDADE DE RECURSOS DE ACESSIBILIDADE/MATERIAIS PARA ELIMINAÇÃO DE BARREIRAS PARA A SALA DE RECURSOS MULTIFUNCIONAIS (SELEÇÃO DE MATERIAIS, EQUIPAMENTOS E MOBILIÁRIO) - DESCRIÇÃO DOS TEM NECESSIDADE DE RECURSOS DE ACESSIBILIDADE/MATERIAIS PARA ELIMINAÇÃO DE BARREIRAS PARA A SALA DE RECURSOS MULTIFUNCIONAIS (SELEÇÃO DE MATERIAIS, EQUIPAMENTOS E MOBILIÁRIO) - DESCRIÇÃO DOS TEM NECESSIDADE DE RECURSOS DE ACESSIBILIDADE/MATERIAIS PARA ELIMINAÇÃO DE BARREIRAS PARA A SALA DE RECURSOS MULTIFUNCIONAIS (SELEÇÃO DE MATERIAIS, EQUIPAMENTOS E MOBILIÁRIO) - DESCRIÇÃO DOS TEM NECESSIDADE DE RECURSOS DE ACESSIBILIDADE/MATERIAIS PARA ELIMINAÇÃO DE BARREIRAS PARA A SALA DE RECURSOS MULTIFUNCIONAIS (SELEÇÃO DE MATERIAIS, EQUIPAMENTOS E MOBILIÁRIO) - DESCRIÇÃO DOS TEM NECESSIDADE DE RECURSOS DE ACESSIBILIDADE/MATERIAIS PARA ELIMINAÇÃO DE BARREIRAS PARA A SALA DE RECURSOS MULTIFUNCIONAIS (SELEÇÃO DE MATERIAIS, EQUIPAMENTOS E MOBILIÁRIO) - DESCRIÇÃO DOS TEM NECESSIDADE DE RECURSOS DE ACESSIBILIDADE/MATERIAIS PARA ELIMINAÇÃO DE BARREIRAS PARA A SALA DE RECURSOS MULTIFUNCIONAIS (SELEÇÃO DE MATERIAIS, EQUIPAMENTOS E MOBILIÁRIO) - DESCRIÇÃO DOS TEM NECESSIDADE DE RECURSOS DE ACESSIBILIDADE/MATERIAIS PARA ELIMINAÇÃO DE BARREIRAS PARA A SALA DE RECURSOS MULTIFUNCIONAIS (SELEÇÃO DE MATERIAIS, EQUIPAMENTOS E MOBILIÁRIO) - DESCRIÇÃO DOS TEM NECESSIDADE DE RECURSOS DE ACESSIBILIDADE/MATERIAIS PARA ELIMINAÇÃO DE BARREIRAS PARA A SALA DE RECURSOS MULTIFUNCIONAIS (SELEÇÃO DE MATERIAIS, EQUIPAMENTOS E MOBILIÁRIO) - DESCRIÇÃO DOS TEM NECESSIDADE DE RECURSOS DE ACESSIBILIDADE/MATERIAIS PARA ELIMINAÇÃO DE BARREIRAS PARA A SALA DE RECURSOS MULTIFUNCIONAIS (SELEÇÃO DE MATERIAIS, EQUIPAMENTOS E MOBILIÁRIO) - DESCRIÇÃO DOS TEM NECESSIDADE DE RECURSOS DE ACESSIBILIDADE/MATERIAIS PARA ELIMINAÇÃO DE BARREIRAS PARA A SALA DE RECURSOS MULTIFUNCIONAIS (SELEÇÃO DE MATERIAIS, EQUIPAMENTOS E MOBILIÁRIO) - DESCRIÇÃO DOS TEM NECESSIDADE DE RECURSOS DE ACESSIBILIDADE/MATERIAIS PARA ELIMINAÇÃO DE BARREIRAS PARA A SALA DE RECURSOS MULTIFUNCIONAIS (SELEÇÃO DE MATERIAIS, EQUIPAMENTOS E MOBILIÁRIO) - DESCRIÇÃO DOS TEM NECESSIDADE DE RECURSOS DE ACESSIBILIDADE/MATERIAIS PARA ELIMINAÇÃO DE BARREIRAS PARA A SALA DE RECURSOS MULTIFUNCIONAIS (SELEÇÃO DE MATERIAIS, EQUIPAMENTOS E MOBILIÁRIO) - DESCRIÇÃO DOS TEM NECESSIDADE DE RECURSOS DE ACESSIBILIDADE/MATERIAIS PARA ELIMINAÇÃO DE BARREIRAS PARA A SALA DE RECURSOS MULTIFUNCIONAIS (SELEÇÃO DE MATERIAIS, EQUIPAMENTOS E MOBILIÁRIO) - "
                        },
                        new QuestaoPlanoAeeDto
                        {
                            Ordem = 9,
                            Questao = "MOBILIZAÇÃO DOS RECURSOS HUMANOS DA U.E. OU PARCERIAS NA UNIDADE EDUCACIONAL",
                            Resposta = "SIM", TipoQuestao = TipoQuestao.Radio,
                            Justificativa =
                                "DESCRIÇÃO DOS MOBILIZAÇÃO DOS RECURSOS HUMANOS DA U.E. OU PARCERIAS NA UNIDADE EDUCACIONAL"
                        },
                        new QuestaoPlanoAeeDto
                        {
                            Ordem = 10,
                            Questao =
                                "MOBILIZAÇÃO DOS RECURSOS HUMANOS COM PROFISSIONAIS EXTERNOS À UNIDADE EDUCACIONAL",
                            Resposta = "SIM", TipoQuestao = TipoQuestao.Radio,
                            Justificativa =
                                "DESCRIÇÃO DOS MOBILIZAÇÃO DOS RECURSOS HUMANOS COM PROFISSIONAIS EXTERNOS À UNIDADE EDUCACIONAL"
                        },
                    }
                },
                Parecer = new ParecerPlanoAeeDto()
                {
                    Cefai = "DESCRIÇÃO DO CEFAI",
                    PaaiResponsavel = "THAYA DE FATIMA BOTELHO (7762577)"
                }
            });
            
            relatorios.Add(new RelatorioPlanoAeeDto()
            {
                Cabecalho = new CabecalhoPlanoAeeDto()
                {
                    AlunoCodigo = "4778773",
                    AlunoNome = "BRUNO PINHEIRO DA SILVA",
                    AnoLetivo = 2022,
                    DreNome = "DRE-BT",
                    UeNome = "CEU EMEF BUTANTA",
                    TurmaNome = "EF-1A",
                    SituacaoPlano = "Encerrado Automaticamente",
                    VersaoPlano = "v2-21/10/2022"
                },
                Cadastro = new CadastroPlanoAeeDto()
                {
                    Responsavel = "TATIANE GONÇALVES FERREIRA SOARES (7951493)",
                    Questoes = new List<QuestaoPlanoAeeDto>()
                    {
                        new QuestaoPlanoAeeDto
                        {
                            Ordem = 1, Questao = "BIMESTRE DE VIGÊNCIA DO PLANO", Resposta = "4º BIMESTRE-2022",
                            TipoQuestao = TipoQuestao.PeriodoEscolar
                        },
                        new QuestaoPlanoAeeDto
                        {
                            Ordem = 2, Questao = "ORGANIZAÇÃO DO AEE", Resposta = "ITINERANTE",
                            TipoQuestao = TipoQuestao.Radio
                        },
                        new QuestaoPlanoAeeDto
                        {
                            Ordem = 3, Questao = "DIAS E HORÁRIOS DE FREQUÊNCIA DO ESTUDANTE NO AEE",
                            Resposta = "EM GRUPO", TipoQuestao = TipoQuestao.FrequenciaEstudanteAEE,
                            FrequenciaAluno = new List<FrequenciaAlunoDto>()
                            {
                                new FrequenciaAlunoDto()
                                    { DiaDaSemana = "SEGUNDA-FEIRA", Inicio = "08:00", Termino = "17:30" },
                                new FrequenciaAlunoDto()
                                    { DiaDaSemana = "TERÇA-FEIRA", Inicio = "09:00", Termino = "16:30" },
                            }
                        },
                        new QuestaoPlanoAeeDto
                        {
                            Ordem = 4, Questao = "FORMAS DE ATENDIMENTO EDUCACIONAL ESPECIALIZADO DO ESTUDANTE",
                            Resposta = "EM GRUPO", TipoQuestao = TipoQuestao.Radio,
                            Justificativa =
                                "JUSTIFICATIVA DE FORMAS DE ATENDIMENTO EDUCACIONAL ESPECIALIZADO DO ESTUDANTE - JUSTIFICATIVA DE FORMAS DE ATENDIMENTO EDUCACIONAL ESPECIALIZADO DO ESTUDANTE - JUSTIFICATIVA DE FORMAS DE ATENDIMENTO EDUCACIONAL ESPECIALIZADO DO ESTUDANTE - JUSTIFICATIVA DE FORMAS DE ATENDIMENTO EDUCACIONAL ESPECIALIZADO DO ESTUDANTE - JUSTIFICATIVA DE FORMAS DE ATENDIMENTO EDUCACIONAL ESPECIALIZADO DO ESTUDANTE - JUSTIFICATIVA DE FORMAS DE ATENDIMENTO EDUCACIONAL ESPECIALIZADO DO ESTUDANTE - JUSTIFICATIVA DE FORMAS DE ATENDIMENTO EDUCACIONAL ESPECIALIZADO DO ESTUDANTE - JUSTIFICATIVA DE FORMAS DE ATENDIMENTO EDUCACIONAL ESPECIALIZADO DO ESTUDANTE - JUSTIFICATIVA DE FORMAS DE ATENDIMENTO EDUCACIONAL ESPECIALIZADO DO ESTUDANTE - JUSTIFICATIVA DE FORMAS DE ATENDIMENTO EDUCACIONAL ESPECIALIZADO DO ESTUDANTE - JUSTIFICATIVA DE FORMAS DE ATENDIMENTO EDUCACIONAL ESPECIALIZADO DO ESTUDANTE - JUSTIFICATIVA DE FORMAS DE ATENDIMENTO EDUCACIONAL ESPECIALIZADO DO ESTUDANTE - JUSTIFICATIVA DE FORMAS DE ATENDIMENTO EDUCACIONAL ESPECIALIZADO DO ESTUDANTE - JUSTIFICATIVA DE FORMAS DE ATENDIMENTO EDUCACIONAL ESPECIALIZADO DO ESTUDANTE - "
                        },
                        new QuestaoPlanoAeeDto
                        {
                            Ordem = 5, Questao = "OBJETIVOS DO AEE",
                            Resposta =
                                "DESCRIÇÃO DOS OBJETIVOS DO AEE - DESCRIÇÃO DOS OBJETIVOS DO AEE - DESCRIÇÃO DOS OBJETIVOS DO AEE - DESCRIÇÃO DOS OBJETIVOS DO AEE - DESCRIÇÃO DOS OBJETIVOS DO AEE - DESCRIÇÃO DOS OBJETIVOS DO AEE - DESCRIÇÃO DOS OBJETIVOS DO AEE - DESCRIÇÃO DOS OBJETIVOS DO AEE - DESCRIÇÃO DOS OBJETIVOS DO AEE - DESCRIÇÃO DOS OBJETIVOS DO AEE - DESCRIÇÃO DOS OBJETIVOS DO AEE - DESCRIÇÃO DOS OBJETIVOS DO AEE - DESCRIÇÃO DOS OBJETIVOS DO AEE - DESCRIÇÃO DOS OBJETIVOS DO AEE - DESCRIÇÃO DOS OBJETIVOS DO AEE - DESCRIÇÃO DOS OBJETIVOS DO AEE - DESCRIÇÃO DOS OBJETIVOS DO AEE - DESCRIÇÃO DOS OBJETIVOS DO AEE - DESCRIÇÃO DOS OBJETIVOS DO AEE - DESCRIÇÃO DOS OBJETIVOS DO AEE - DESCRIÇÃO DOS OBJETIVOS DO AEE - DESCRIÇÃO DOS OBJETIVOS DO AEE - DESCRIÇÃO DOS OBJETIVOS DO AEE - DESCRIÇÃO DOS OBJETIVOS DO AEE - DESCRIÇÃO DOS OBJETIVOS DO AEE - DESCRIÇÃO DOS OBJETIVOS DO AEE - DESCRIÇÃO DOS OBJETIVOS DO AEE - DESCRIÇÃO DOS OBJETIVOS DO AEE - DESCRIÇÃO DOS OBJETIVOS DO AEE - DESCRIÇÃO DOS OBJETIVOS DO AEE - DESCRIÇÃO DOS OBJETIVOS DO AEE - DESCRIÇÃO DOS OBJETIVOS DO AEE - DESCRIÇÃO DOS OBJETIVOS DO AEE - DESCRIÇÃO DOS OBJETIVOS DO AEE - DESCRIÇÃO DOS OBJETIVOS DO AEE - DESCRIÇÃO DOS OBJETIVOS DO AEE - DESCRIÇÃO DOS OBJETIVOS DO AEE - ",
                            TipoQuestao = TipoQuestao.Texto
                        },
                        new QuestaoPlanoAeeDto
                        {
                            Ordem = 6, Questao = "ORIENTAÇÕES DE AÇÕES PARA O DESENVOLVIMENTO/ATIVIDADE DO AEE",
                            Resposta =
                                "DESCRIÇÃO DOS ORIENTAÇÕES DE AÇÕES PARA O DESENVOLVIMENTO/ATIVIDADE DO AEE - DESCRIÇÃO DOS ORIENTAÇÕES DE AÇÕES PARA O DESENVOLVIMENTO/ATIVIDADE DO AEE - DESCRIÇÃO DOS ORIENTAÇÕES DE AÇÕES PARA O DESENVOLVIMENTO/ATIVIDADE DO AEE - DESCRIÇÃO DOS ORIENTAÇÕES DE AÇÕES PARA O DESENVOLVIMENTO/ATIVIDADE DO AEE - DESCRIÇÃO DOS ORIENTAÇÕES DE AÇÕES PARA O DESENVOLVIMENTO/ATIVIDADE DO AEE - DESCRIÇÃO DOS ORIENTAÇÕES DE AÇÕES PARA O DESENVOLVIMENTO/ATIVIDADE DO AEE - DESCRIÇÃO DOS ORIENTAÇÕES DE AÇÕES PARA O DESENVOLVIMENTO/ATIVIDADE DO AEE - DESCRIÇÃO DOS ORIENTAÇÕES DE AÇÕES PARA O DESENVOLVIMENTO/ATIVIDADE DO AEE - DESCRIÇÃO DOS ORIENTAÇÕES DE AÇÕES PARA O DESENVOLVIMENTO/ATIVIDADE DO AEE - DESCRIÇÃO DOS ORIENTAÇÕES DE AÇÕES PARA O DESENVOLVIMENTO/ATIVIDADE DO AEE - DESCRIÇÃO DOS ORIENTAÇÕES DE AÇÕES PARA O DESENVOLVIMENTO/ATIVIDADE DO AEE - DESCRIÇÃO DOS ORIENTAÇÕES DE AÇÕES PARA O DESENVOLVIMENTO/ATIVIDADE DO AEE - DESCRIÇÃO DOS ORIENTAÇÕES DE AÇÕES PARA O DESENVOLVIMENTO/ATIVIDADE DO AEE - DESCRIÇÃO DOS ORIENTAÇÕES DE AÇÕES PARA O DESENVOLVIMENTO/ATIVIDADE DO AEE - DESCRIÇÃO DOS ORIENTAÇÕES DE AÇÕES PARA O DESENVOLVIMENTO/ATIVIDADE DO AEE - DESCRIÇÃO DOS ORIENTAÇÕES DE AÇÕES PARA O DESENVOLVIMENTO/ATIVIDADE DO AEE - DESCRIÇÃO DOS ORIENTAÇÕES DE AÇÕES PARA O DESENVOLVIMENTO/ATIVIDADE DO AEE - DESCRIÇÃO DOS ORIENTAÇÕES DE AÇÕES PARA O DESENVOLVIMENTO/ATIVIDADE DO AEE - ",
                            TipoQuestao = TipoQuestao.Texto
                        },
                        new QuestaoPlanoAeeDto
                        {
                            Ordem = 7,
                            Questao =
                                "TEM NECESSIDADE DE RECURSOS DE ACESSIBILIDADE/MATERIAIS PARA ELIMINAÇÃO DE BARREIRAS PARA A SALA REGULAR (SELEÇÃO DE MATERIAIS, EQUIPAMENTOS E MOBILIÁRIO)",
                            Resposta = "SIM", TipoQuestao = TipoQuestao.Radio,
                            Justificativa =
                                "DESCRIÇÃO DOS TEM NECESSIDADE DE RECURSOS DE ACESSIBILIDADE/MATERIAIS PARA ELIMINAÇÃO DE BARREIRAS PARA A SALA REGULAR (SELEÇÃO DE MATERIAIS, EQUIPAMENTOS E MOBILIÁRIO)"
                        },
                        new QuestaoPlanoAeeDto
                        {
                            Ordem = 8,
                            Questao =
                                "TEM NECESSIDADE DE RECURSOS DE ACESSIBILIDADE/MATERIAIS PARA ELIMINAÇÃO DE BARREIRAS PARA A SALA DE RECURSOS MULTIFUNCIONAIS (SELEÇÃO DE MATERIAIS, EQUIPAMENTOS E MOBILIÁRIO)",
                            Resposta = "SIM", TipoQuestao = TipoQuestao.Radio,
                            Justificativa =
                                "DESCRIÇÃO DOS TEM NECESSIDADE DE RECURSOS DE ACESSIBILIDADE/MATERIAIS PARA ELIMINAÇÃO DE BARREIRAS PARA A SALA DE RECURSOS MULTIFUNCIONAIS (SELEÇÃO DE MATERIAIS, EQUIPAMENTOS E MOBILIÁRIO) - DESCRIÇÃO DOS TEM NECESSIDADE DE RECURSOS DE ACESSIBILIDADE/MATERIAIS PARA ELIMINAÇÃO DE BARREIRAS PARA A SALA DE RECURSOS MULTIFUNCIONAIS (SELEÇÃO DE MATERIAIS, EQUIPAMENTOS E MOBILIÁRIO) - DESCRIÇÃO DOS TEM NECESSIDADE DE RECURSOS DE ACESSIBILIDADE/MATERIAIS PARA ELIMINAÇÃO DE BARREIRAS PARA A SALA DE RECURSOS MULTIFUNCIONAIS (SELEÇÃO DE MATERIAIS, EQUIPAMENTOS E MOBILIÁRIO) - DESCRIÇÃO DOS TEM NECESSIDADE DE RECURSOS DE ACESSIBILIDADE/MATERIAIS PARA ELIMINAÇÃO DE BARREIRAS PARA A SALA DE RECURSOS MULTIFUNCIONAIS (SELEÇÃO DE MATERIAIS, EQUIPAMENTOS E MOBILIÁRIO) - DESCRIÇÃO DOS TEM NECESSIDADE DE RECURSOS DE ACESSIBILIDADE/MATERIAIS PARA ELIMINAÇÃO DE BARREIRAS PARA A SALA DE RECURSOS MULTIFUNCIONAIS (SELEÇÃO DE MATERIAIS, EQUIPAMENTOS E MOBILIÁRIO) - DESCRIÇÃO DOS TEM NECESSIDADE DE RECURSOS DE ACESSIBILIDADE/MATERIAIS PARA ELIMINAÇÃO DE BARREIRAS PARA A SALA DE RECURSOS MULTIFUNCIONAIS (SELEÇÃO DE MATERIAIS, EQUIPAMENTOS E MOBILIÁRIO) - DESCRIÇÃO DOS TEM NECESSIDADE DE RECURSOS DE ACESSIBILIDADE/MATERIAIS PARA ELIMINAÇÃO DE BARREIRAS PARA A SALA DE RECURSOS MULTIFUNCIONAIS (SELEÇÃO DE MATERIAIS, EQUIPAMENTOS E MOBILIÁRIO) - DESCRIÇÃO DOS TEM NECESSIDADE DE RECURSOS DE ACESSIBILIDADE/MATERIAIS PARA ELIMINAÇÃO DE BARREIRAS PARA A SALA DE RECURSOS MULTIFUNCIONAIS (SELEÇÃO DE MATERIAIS, EQUIPAMENTOS E MOBILIÁRIO) - DESCRIÇÃO DOS TEM NECESSIDADE DE RECURSOS DE ACESSIBILIDADE/MATERIAIS PARA ELIMINAÇÃO DE BARREIRAS PARA A SALA DE RECURSOS MULTIFUNCIONAIS (SELEÇÃO DE MATERIAIS, EQUIPAMENTOS E MOBILIÁRIO) - DESCRIÇÃO DOS TEM NECESSIDADE DE RECURSOS DE ACESSIBILIDADE/MATERIAIS PARA ELIMINAÇÃO DE BARREIRAS PARA A SALA DE RECURSOS MULTIFUNCIONAIS (SELEÇÃO DE MATERIAIS, EQUIPAMENTOS E MOBILIÁRIO) - DESCRIÇÃO DOS TEM NECESSIDADE DE RECURSOS DE ACESSIBILIDADE/MATERIAIS PARA ELIMINAÇÃO DE BARREIRAS PARA A SALA DE RECURSOS MULTIFUNCIONAIS (SELEÇÃO DE MATERIAIS, EQUIPAMENTOS E MOBILIÁRIO) - DESCRIÇÃO DOS TEM NECESSIDADE DE RECURSOS DE ACESSIBILIDADE/MATERIAIS PARA ELIMINAÇÃO DE BARREIRAS PARA A SALA DE RECURSOS MULTIFUNCIONAIS (SELEÇÃO DE MATERIAIS, EQUIPAMENTOS E MOBILIÁRIO) - DESCRIÇÃO DOS TEM NECESSIDADE DE RECURSOS DE ACESSIBILIDADE/MATERIAIS PARA ELIMINAÇÃO DE BARREIRAS PARA A SALA DE RECURSOS MULTIFUNCIONAIS (SELEÇÃO DE MATERIAIS, EQUIPAMENTOS E MOBILIÁRIO) - DESCRIÇÃO DOS TEM NECESSIDADE DE RECURSOS DE ACESSIBILIDADE/MATERIAIS PARA ELIMINAÇÃO DE BARREIRAS PARA A SALA DE RECURSOS MULTIFUNCIONAIS (SELEÇÃO DE MATERIAIS, EQUIPAMENTOS E MOBILIÁRIO) - DESCRIÇÃO DOS TEM NECESSIDADE DE RECURSOS DE ACESSIBILIDADE/MATERIAIS PARA ELIMINAÇÃO DE BARREIRAS PARA A SALA DE RECURSOS MULTIFUNCIONAIS (SELEÇÃO DE MATERIAIS, EQUIPAMENTOS E MOBILIÁRIO) - DESCRIÇÃO DOS TEM NECESSIDADE DE RECURSOS DE ACESSIBILIDADE/MATERIAIS PARA ELIMINAÇÃO DE BARREIRAS PARA A SALA DE RECURSOS MULTIFUNCIONAIS (SELEÇÃO DE MATERIAIS, EQUIPAMENTOS E MOBILIÁRIO) - "
                        },
                        new QuestaoPlanoAeeDto
                        {
                            Ordem = 9,
                            Questao = "MOBILIZAÇÃO DOS RECURSOS HUMANOS DA U.E. OU PARCERIAS NA UNIDADE EDUCACIONAL",
                            Resposta = "SIM", TipoQuestao = TipoQuestao.Radio,
                            Justificativa =
                                "DESCRIÇÃO DOS MOBILIZAÇÃO DOS RECURSOS HUMANOS DA U.E. OU PARCERIAS NA UNIDADE EDUCACIONAL"
                        },
                        new QuestaoPlanoAeeDto
                        {
                            Ordem = 10,
                            Questao =
                                "MOBILIZAÇÃO DOS RECURSOS HUMANOS COM PROFISSIONAIS EXTERNOS À UNIDADE EDUCACIONAL",
                            Resposta = "SIM", TipoQuestao = TipoQuestao.Radio,
                            Justificativa =
                                "DESCRIÇÃO DOS MOBILIZAÇÃO DOS RECURSOS HUMANOS COM PROFISSIONAIS EXTERNOS À UNIDADE EDUCACIONAL"
                        },
                    }
                },
                Parecer = new ParecerPlanoAeeDto()
                {}
            });
            
            await mediator.Send(new GerarRelatorioHtmlPDFPlanoAeeCommand(relatorios, request.CodigoCorrelacao));
        }
    }
}