version: '3.4'

services:
  sme.sr.workers.sgp:
    image: ${DOCKER_REGISTRY-}smesrworkerssgp
    build:
      context: .
      dockerfile: src/SME.SR.Workers.SGP/Dockerfile
networks:
  sme-network:
    driver: bridge
    name: sme_external_network
