version: '3'
services:

##########################################################
### JRS - Jasper Reports Server ##########################
##########################################################
  mariadb:
    image: 'bitnami/mariadb:10.3'
    environment:
      - MARIADB_USER=jasperreports
      - MARIADB_DATABASE=jasperreports
      - ALLOW_EMPTY_PASSWORD=yes
    #volumes:
    #  - 'mariadb_data:/volumes/mariadb:Z'

  jasper_reports_server:
    container_name: jasper_reports_server
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - JASPERREPORTS_DATABASE_USER=jasperreports
      - JASPERREPORTS_DATABASE_NAME=jasperreports
      - ALLOW_EMPTY_PASSWORD=yes
    image: bitnami/jasperreports:7.2.0
    #volumes:
    #  - 'jasperreports_data:/volumes/jasperreports:Z'
    networks:
      - default
    ports:
      - "8080:8080"
      - "8443:8443"
    depends_on:
      - mariadb

##########################################################
### Volumes, rede e infra estrutura ######################
##########################################################
volumes:
  jasperreports_data:
    driver: local
  mariadb_data:
    driver: local

networks:
  default:
    driver: bridge
