version: "3"
services:
  ##########################################################
  ### Servidor de Relatorios - Jasper + RabbitMQ ###########
  ##########################################################

  ### Mensageria ###########################################
  ##########################################################
  sme_sr_rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.7-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=bitnami
    networks:
      - default
    ports:
      - "5672:5672"
      - "15672:15672"  
networks:
  default:
    driver: bridge
