[Environment]::SetEnvironmentVariable("Sentry__DSN", "XXX", "Machine")
[Environment]::SetEnvironmentVariable("CoreSSOConnection", "Server=10.49.19.159;Database=CoreSSO;User Id=UserCoreSSO;Password=Sgp1234;", "Machine")
[Environment]::SetEnvironmentVariable("EolConnection", "Server=db_educacao.rede.sp;Database=se1426;User Id=user_se1426_cotic;Password=3ol_c0tic@;MultiSubnetFailover=Yes;ApplicationIntent=ReadOnly;", "Machine")
[Environment]::SetEnvironmentVariable("ApiEolConnection", "User ID=postgres;Password=postgres;Host=localhost;Port=5432;Database=eol_db;Pooling=true", "Machine")
[Environment]::SetEnvironmentVariable("ConnectionStrings__SGP-Postgres", "User ID=postgres;Password=postgres;Host=localhost;Port=5432;Database=sgp_db;Pooling=true", "Machine")
[Environment]::SetEnvironmentVariable("ConfiguracaoRabbit__HostName", "localhost", "Machine")
[Environment]::SetEnvironmentVariable("ConfiguracaoRabbit__UserName", "user", "Machine")
[Environment]::SetEnvironmentVariable("ConfiguracaoRabbit__Password", "bitnami", "Machine")
[Environment]::SetEnvironmentVariable("ConfiguracaoJasper__Hostname", "http://127.0.0.1:8080", "Machine")
[Environment]::SetEnvironmentVariable("ConfiguracaoJasper__Username", "user", "Machine")
[Environment]::SetEnvironmentVariable("ConfiguracaoJasper__Password", "bitnami", "Machine")
